import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Check, CircleHelp, Loader2, X } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export function PackExecutionPanel() {
  const utils = trpc.useUtils();
  const execution = trpc.creatorPacks.myExecution.useQuery();
  const [detail, setDetail] = useState("");
  const feedback = trpc.creatorPacks.recordExecutionFeedback.useMutation({ onSuccess: async (_, input) => { await Promise.all([utils.creatorPacks.myExecution.invalidate(), utils.creatorPacks.myJourney.invalidate(), utils.skootly.workspace.invalidate()]); setDetail(""); toast.success(input.feedbackStatus === "done" ? "Progress saved. Skootly is ready for your next step." : input.feedbackStatus === "stuck" ? "Your coach can see that you need a hand." : "Not today is noted. Return when this step is possible."); }, onError: error => toast.error(error.message) });
  if (execution.isLoading) return <section className="pack-journey"><Loader2 className="size-5 animate-spin" />Finding your Pack path…</section>;
  if (!execution.data) return null;
  const { current, milestones, blueprint, packName, creatorName, versionNumber, enrollment } = execution.data;
  if (!current) return <section className="pack-journey"><span className="mini-label">PACK COMPLETE</span><h1>You completed {packName}.</h1><p className="pack-journey__provenance">{creatorName}’s path · Version {versionNumber}</p><article className="journey-question"><h2>Take a moment to notice what moved.</h2><p>Your coach can see that the Pack is complete. Your next decision can be intentional instead of automatic.</p></article></section>;
  const progress = Math.min(100, ((current.position - 1) / Math.max(milestones.length, 1)) * 100);
  return <section className="pack-journey"><span className="mini-label">YOUR COACH-GUIDED PATH</span><h1>{blueprint?.destination || packName}</h1><p className="pack-journey__provenance">{creatorName}’s {packName} · Version {versionNumber}</p><div className="journey-progress"><span>Step {current.position} of {milestones.length} · {current.title}</span><div><i style={{ width: `${progress}%` }} /></div></div><article className="journey-question"><span className="card-kicker">YOUR NEXT SKOOT</span><h2>{current.defaultSkoot}</h2><p><b>Done looks like:</b> {current.definitionOfDone}</p>{current.supportingSkoot ? <p className="rounded-xl bg-[#f2edff] p-3 text-sm"><b>Only if it helps:</b> {current.supportingSkoot}</p> : null}{current.assetSpec ? <p className="rounded-xl bg-[#fff2bd] p-3 text-sm"><b>Asset instructions:</b> {current.assetSpec}</p> : null}{current.resourceUrl ? <a className="mt-3 inline-block text-sm font-bold underline" href={current.resourceUrl} target="_blank" rel="noreferrer">Open your coach-provided resource</a> : null}<div className="mt-5 rounded-xl border-2 border-black bg-white p-3"><label className="text-sm font-bold">{current.feedbackPrompt}</label><Textarea className="mt-2" value={detail} onChange={event => setDetail(event.target.value)} placeholder="A short honest update is enough." maxLength={3000} /></div><div className="mt-3 flex flex-wrap gap-2"><Button disabled={feedback.isPending} onClick={() => feedback.mutate({ feedbackStatus: "done", detail })}>{feedback.isPending ? <Loader2 className="size-4 animate-spin" /> : <Check className="size-4" />} I did it</Button><Button variant="outline" disabled={feedback.isPending} onClick={() => feedback.mutate({ feedbackStatus: "stuck", detail })}><CircleHelp className="size-4" /> I’m stuck</Button><Button variant="ghost" disabled={feedback.isPending} onClick={() => feedback.mutate({ feedbackStatus: "not_today", detail })}><X className="size-4" /> Not today</Button></div></article><article className="not-today-card"><div><span className="card-kicker">NOT TODAY</span><p>{current.notToday || blueprint?.notToday || "Do not jump ahead. Your current step is enough."}</p></div><span className="text-xs font-bold text-stone-500">Enrolled path · step {enrollment.currentMilestonePosition}</span></article></section>;
}
