import { useAuth } from "@/_core/hooks/useAuth";
import { CreatorSupportPanel } from "@/components/CreatorSupportPanel";
import { GuidedPackBuilder } from "@/components/GuidedPackBuilder";
import { MemphisShapes, SkootlyHeader } from "@/components/SkootlyHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Check, ClipboardCopy, CopyPlus, Lightbulb, Loader2, Plus, Send, Trash2, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

const blankPack = { name: "", description: "" };
const labelFor = (kind: string) => kind.replace(/_/g, " ");
const date = (value?: number) => value ? new Date(value).toLocaleDateString() : "—";

export default function CreatorPacks() {
  const { user, loading } = useAuth();
  const [, setLocation] = useLocation();
  const utils = trpc.useUtils();
  const packsQuery = trpc.creatorPacks.list.useQuery(undefined, { enabled: Boolean(user) });
  const insights = trpc.creatorPacks.insights.useQuery(undefined, { enabled: Boolean(user) });
  const onboarding = trpc.creatorPacks.onboarding.useQuery(undefined, { enabled: Boolean(user) });
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const [newOpen, setNewOpen] = useState(false);
  const [guidedOpen, setGuidedOpen] = useState(false);
  const [packForm, setPackForm] = useState(blankPack);
  const [teaching, setTeaching] = useState("");
  const [editingProposalId, setEditingProposalId] = useState<number | null>(null);
  const [editingProposalContent, setEditingProposalContent] = useState("");
  const [creatorInviteEmail, setCreatorInviteEmail] = useState("");
  const [creatorInviteLink, setCreatorInviteLink] = useState("");
  const packs = packsQuery.data ?? [];
  const selected = useMemo(() => packs.find(pack => pack.id === selectedId) ?? null, [packs, selectedId]);
  const proposals = trpc.creatorPacks.listProposals.useQuery({ packId: selectedId ?? 0 }, { enabled: Boolean(selectedId) });
  const creatorInvites = trpc.creatorPacks.listCreatorInvites.useQuery(undefined, { enabled: Boolean(user) });
  useEffect(() => { if (!selectedId && packs[0]) setSelectedId(packs[0].id); }, [packs, selectedId]);
  useEffect(() => {
    if (!loading && user && !onboarding.isLoading && !onboarding.data) setLocation("/onboarding?entry=creator");
  }, [loading, onboarding.data, onboarding.isLoading, setLocation, user]);
  const refresh = async () => { await utils.creatorPacks.list.invalidate(); await utils.creatorPacks.insights.invalidate(); if (selectedId) await utils.creatorPacks.listProposals.invalidate({ packId: selectedId }); };
  const create = trpc.creatorPacks.create.useMutation({ onSuccess: async result => { await refresh(); setSelectedId(result.packId); setPackForm(blankPack); setNewOpen(false); toast.success("Creator Pack created. Teach Skootly the first rule."); }, onError: error => toast.error(error.message) });
  const propose = trpc.creatorPacks.propose.useMutation({ onSuccess: async () => { await refresh(); setTeaching(""); toast.success("Knowledge proposal ready for review."); }, onError: error => toast.error(error.message) });
  const approve = trpc.creatorPacks.approve.useMutation({ onSuccess: refresh, onError: error => toast.error(error.message) });
  const cancel = trpc.creatorPacks.cancel.useMutation({ onSuccess: refresh, onError: error => toast.error(error.message) });
  const createCreatorInvite = trpc.creatorPacks.createCreatorInvite.useMutation({ onSuccess: async result => { setCreatorInviteLink(`${window.location.origin}/creator/join/${result.token}`); setCreatorInviteEmail(""); await utils.creatorPacks.listCreatorInvites.invalidate(); toast.success("Creator invitation link created. Copy it to send manually."); }, onError: error => toast.error(error.message) });
  const createPilotCreatorInvite = trpc.creatorPacks.createPilotCreatorInvite.useMutation({ onSuccess: async result => { setCreatorInviteLink(`${window.location.origin}/creator/join/${result.token}`); setCreatorInviteEmail(""); await utils.creatorPacks.listCreatorInvites.invalidate(); toast.success("One-creator pilot link created. Copy it to send manually."); }, onError: error => toast.error(error.message === "PILOT_INVITE_ALREADY_ACTIVE" ? "Your one-creator pilot is already active. Revoke or wait for it to expire before creating another." : error.message) });
  const restartOnboarding = trpc.creatorPacks.restartOnboarding.useMutation({ onSuccess: async () => { await utils.creatorPacks.onboarding.invalidate(); setLocation("/onboarding?rehearse=1"); }, onError: error => toast.error(error.message) });
  const revokeCreatorInvite = trpc.creatorPacks.revokeCreatorInvite.useMutation({ onSuccess: async () => { await utils.creatorPacks.listCreatorInvites.invalidate(); toast.success("Creator invitation revoked."); }, onError: error => toast.error(error.message) });
  const activePilotInvite = creatorInvites.data?.find(invite => invite.status === "pending") ?? null;
  if (loading || packsQuery.isLoading || onboarding.isLoading) return <div className="creator-loading"><Loader2 className="animate-spin" /> Preparing your Creator workspace…</div>;
  if (!user) return <div className="creator-loading">Sign in to create a Pack.</div>;
  if (!onboarding.data) return <div className="creator-loading"><Loader2 className="animate-spin" /> Opening Coach setup…</div>;

  return <div className="creator-page"><SkootlyHeader /><MemphisShapes quiet /><main className="creator-shell">
    <section className="creator-hero"><div><p className="eyebrow">CREATOR MODE</p><h1>Teach Skootly once.<br />Students get a clearer next move.</h1><p>Turn your evolving method into a short, reviewable execution path—not a giant prompt document.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={restartOnboarding.isPending} onClick={() => restartOnboarding.mutate()}>Test Coach setup again</Button><Button onClick={() => setGuidedOpen(true)}><Plus className="size-4" /> Build a Skoot Pack</Button></div></section>
    <section className="mb-6 rounded-[1.5rem] border-[3px] border-black bg-[#fff2bd] p-4 shadow-[5px_5px_0_#b9a7ff] sm:p-5"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><p className="card-kicker">YOUR CREATOR LAUNCH</p><h2 className="mt-1 text-xl font-black">Shape → preview → approve → invite</h2><p className="mt-1 max-w-2xl text-sm text-stone-700">Keep the first launch small: one Pack, one clear student outcome, and one student invite. Your pilot creator receives their own private Skootly workspace—not access to yours.</p></div><div className="flex flex-wrap gap-2 text-xs font-bold"><span className="rounded-full border-2 border-black bg-white px-3 py-1">1. Shape</span><span className="rounded-full border-2 border-black bg-white px-3 py-1">2. Preview</span><span className="rounded-full border-2 border-black bg-white px-3 py-1">3. Approve</span><span className="rounded-full border-2 border-black bg-white px-3 py-1">4. Invite</span></div></div><div className="mt-4 border-t-2 border-black pt-4"><div className="flex flex-col gap-2 sm:flex-row sm:items-end"><Label className="flex-1">Invite one pilot creator<Input value={creatorInviteEmail} onChange={event => setCreatorInviteEmail(event.target.value)} type="email" placeholder="creator@example.com" /></Label><Button disabled={!creatorInviteEmail || Boolean(activePilotInvite) || createPilotCreatorInvite.isPending} onClick={() => createPilotCreatorInvite.mutate({ email: creatorInviteEmail, expiresInDays: 7 })}>{createPilotCreatorInvite.isPending ? <Loader2 className="size-4 animate-spin" /> : <Send className="size-4" />} {activePilotInvite ? "Pilot invite active" : "Create 7-day pilot link"}</Button></div><p className="mt-2 text-xs text-stone-600">Start with one independent creator. The secure link works only for this exact email address and never shares your Packs or students.</p>{creatorInviteLink ? <div className="mt-3 rounded-xl border-2 border-black bg-white p-3"><p className="break-all text-sm font-semibold">{creatorInviteLink}</p><Button size="sm" className="mt-2" onClick={async () => { await navigator.clipboard.writeText(creatorInviteLink); toast.success("Creator invitation copied."); }}><ClipboardCopy className="size-3" /> Copy pilot link</Button></div> : null}{creatorInvites.data?.length ? <div className="mt-3 grid gap-2">{creatorInvites.data.slice(0, 4).map(invite => <div key={invite.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl border-2 border-black bg-white px-3 py-2 text-sm"><span><b>{invite.email}</b> · {invite.status} · expires {new Date(invite.expiresAt).toLocaleDateString()}</span>{invite.status === "pending" ? <Button size="sm" type="button" variant="outline" disabled={revokeCreatorInvite.isPending} onClick={() => revokeCreatorInvite.mutate({ inviteId: invite.id })}><Trash2 className="size-3" /> Revoke</Button> : null}</div>)}</div> : null}</div></section>
    <div className="creator-layout"><aside className="creator-pack-list"><div className="creator-list-heading"><span>Your Packs</span><Button size="icon" variant="outline" onClick={() => setGuidedOpen(true)} aria-label="Build a Skoot Pack"><Plus className="size-4" /></Button></div>{packs.length ? packs.map(pack => <button key={pack.id} onClick={() => setSelectedId(pack.id)} className={pack.id === selectedId ? "creator-pack-item creator-pack-item--active" : "creator-pack-item"}><b>{pack.name}</b><span>Version {pack.activeVersion?.versionNumber ?? 1} · {pack.assignments.length} student{pack.assignments.length === 1 ? "" : "s"}</span></button>) : <div className="creator-list-empty"><Lightbulb className="size-5" />Start with one Pack for one method.</div>}</aside>
      <section className="creator-workspace">{selected ? <><div className="creator-pack-heading"><div><p className="card-kicker">CURRENT PACK</p><h2>{selected.name}</h2><p>{selected.description || "Add a short description to clarify this method."}</p></div><div className="flex flex-wrap items-center gap-2"><Badge variant="outline">Version {selected.activeVersion?.versionNumber ?? 1} · updated {date(selected.updatedAt)}</Badge><Button size="sm" onClick={() => setGuidedOpen(true)}>Build / update path</Button></div></div>
        <article className="creator-teach-card"><div><p className="card-kicker">TEACH SKOOTLY</p><h3>What changed in your method?</h3><p>Say it naturally. Skootly makes a reviewable proposal; student guidance never changes silently.</p></div><Textarea value={teaching} onChange={event => setTeaching(event.target.value)} placeholder="I’ve learned that students should speak to 10 potential buyers before building their webinar." /><Button disabled={!teaching.trim() || propose.isPending} onClick={() => selectedId && propose.mutate({ packId: selectedId, sourceText: teaching })}>{propose.isPending ? <Loader2 className="size-4 animate-spin" /> : <CopyPlus className="size-4" />} Propose Pack update</Button></article>
        <section className="creator-proposals"><div className="section-heading"><div><p className="card-kicker">REVIEW BEFORE PUBLISHING</p><h3>Pending knowledge</h3></div><span>{proposals.data?.length ?? 0} pending</span></div>{proposals.data?.length ? proposals.data.map(item => <article className="creator-proposal" key={item.id}><div><Badge>{labelFor(item.proposedType)}</Badge><p className="proposal-source">“{item.sourceText}”</p>{editingProposalId === item.id ? <Textarea aria-label="Edit proposed Pack knowledge" value={editingProposalContent} onChange={event => setEditingProposalContent(event.target.value)} /> : <h4>{item.proposedContent}</h4>}</div><div className="proposal-actions">{editingProposalId === item.id ? <><Button size="sm" disabled={approve.isPending || !editingProposalContent.trim()} onClick={() => approve.mutate({ proposalId: item.id, content: editingProposalContent.trim() }, { onSuccess: () => { setEditingProposalId(null); setEditingProposalContent(""); } })}><Check className="size-3" /> Save & add</Button><Button size="sm" variant="outline" onClick={() => { setEditingProposalId(null); setEditingProposalContent(""); }}>Cancel edit</Button></> : <><Button size="sm" disabled={approve.isPending} onClick={() => approve.mutate({ proposalId: item.id })}><Check className="size-3" /> Add to Pack</Button><Button size="sm" variant="outline" onClick={() => { setEditingProposalId(item.id); setEditingProposalContent(item.proposedContent); }}>Edit</Button><Button size="sm" variant="outline" onClick={() => cancel.mutate({ proposalId: item.id })}><X className="size-3" /> Ignore</Button></>}</div></article>) : <div className="creator-empty-state">Your reviewable knowledge proposals will appear here.</div>}</section>
        <section className="creator-assign"><div><p className="card-kicker">ENROLL STUDENTS</p><h3>Create one private link per student.</h3><p>Open <b>Build / update path</b> above, then create an expiring invite after approving the Pack. Each student accepts their own link and stays pinned to that Pack version.</p></div>{selected.assignments.length ? <div className="student-chips">{selected.assignments.map(student => <span key={student.id}>{student.name || student.email || `Student #${student.studentUserId}`} <small>legacy assignment</small></span>)}</div> : null}</section>
        <CreatorSupportPanel />
      </> : <div className="creator-start"><Lightbulb className="size-8" /><h2>Create the first living Skoot Pack.</h2><p>Choose a short Pack shape, edit the path until it sounds like you, then approve it before anyone sees it.</p><Button onClick={() => setGuidedOpen(true)}>Build a Pack</Button></div>}</section>
      <aside className="creator-insights"><p className="card-kicker">EARLY SIGNALS</p><h2>What your students are experiencing</h2><div className="insight-number"><b>{insights.data?.assignedStudents ?? 0}</b><span>assigned student{(insights.data?.assignedStudents ?? 0) === 1 ? "" : "s"}</span></div><div className="insight-block"><h3>Getting stuck on</h3>{insights.data?.bottlenecks?.length ? insights.data.bottlenecks.map(item => <p key={item.label}>{item.label}<b>{item.count}</b></p>) : <p className="muted">Student check-ins will reveal patterns here.</p>}</div><div className="insight-block"><h3>Repeated questions</h3>{insights.data?.repeatedQuestions?.length ? insights.data.repeatedQuestions.map(item => <p key={item.label}>{item.label}<b>{item.count}</b></p>) : <p className="muted">Private conversations will contribute anonymous themes here.</p>}</div><div className="insight-block"><h3>Possible misconceptions</h3>{insights.data?.misconceptions?.length ? insights.data.misconceptions.map(item => <p key={item.label}>{item.label}<b>{item.count}</b></p>) : <p className="muted">Point A answers will surface anonymous belief patterns.</p>}</div><div className="insight-block"><h3>Frequently skipped</h3>{insights.data?.skippedSkoots?.length ? insights.data.skippedSkoots.map(item => <p key={item.label}>{item.label}<b>{item.count}</b></p>) : <p className="muted">Skipped Skoot patterns will appear here.</p>}</div><div className="insight-block"><h3>Stored outcomes</h3>{insights.data?.outcomeSummary?.length ? insights.data.outcomeSummary.map(item => <p key={item.label}>{labelFor(item.label)}<b>{item.count}</b></p>) : <p className="muted">Completed outcomes will summarize here.</p>}</div><div className="insight-block"><h3>Asking for human help</h3>{insights.data?.escalationRequests?.length ? insights.data.escalationRequests.map(item => <p key={item.label}>{item.label}<b>{item.count}</b></p>) : <p className="muted">Anonymous escalation patterns will appear here.</p>}</div></aside>
    </div>
  </main><Dialog open={newOpen} onOpenChange={setNewOpen}><DialogContent><DialogHeader><DialogTitle>Create a Skoot Pack</DialogTitle><DialogDescription>One Pack represents one evolving method. You can update it without asking students to copy a new prompt.</DialogDescription></DialogHeader><div className="creator-new-form"><Label>Pack name<Input value={packForm.name} onChange={event => setPackForm({ ...packForm, name: event.target.value })} placeholder="Launch Skoot Pack" /></Label><Label>What is it for?<Textarea value={packForm.description} onChange={event => setPackForm({ ...packForm, description: event.target.value })} placeholder="Decision rules for validating and launching a new offer." /></Label><Button disabled={!packForm.name.trim() || create.isPending} onClick={() => create.mutate(packForm)}>{create.isPending ? "Creating…" : "Create Pack"}</Button></div></DialogContent></Dialog><Dialog open={guidedOpen} onOpenChange={setGuidedOpen}><DialogContent className="max-h-[92vh] max-w-5xl overflow-y-auto"><DialogHeader><DialogTitle>{selected ? "Build the path your students will follow" : "Start with a short Pack shape"}</DialogTitle><DialogDescription>You can change every word. Nothing reaches students until you approve a version.</DialogDescription></DialogHeader><GuidedPackBuilder packId={selectedId} onPublished={async newPackId => { await refresh(); setSelectedId(newPackId); setGuidedOpen(false); }} /></DialogContent></Dialog></div>;
}
